version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - '80:80'
    volumes:
      - './src/app:/var/www/html'
    networks:
      - net

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - '3306:3306'
    networks:
      - net
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'dbv:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

volumes:
  dbv:
    driver: local

networks:
  net:
    driver: bridge
    name: net
